import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

// Configure Outfit font
const outfit = Outfit({
  weight: ["400"], // Specify the weights you want to use (e.g., 400 for regular)
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
      <Header/>
        {children}
      </body>
    </html>
  );
}
